# image will be published to ghcr.io/<user>/<name>
name: ublahaj
# description will be included in the image's metadata
description: uBlue based custom image, but it's for shorks, and it's blue. So it's uBlahaj.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/stefan-maassen/wezterm/repo/fedora-39/stefan-maassen-wezterm-fedora-%OS_VERSION%.repo
    install:
      - btop
      - foot
      - wezterm
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    remove:
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - htop
      - toolbox

  - type: fonts
    fonts:
      nerd-fonts:
        - Agave

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

